Dockerfile
build.sh
dcos-log/Makefile
dcos-log/api/handlers.go
dcos-log/api/routes.go
dcos-log/api/server.go
dcos-log/config/config.go
dcos-log/dcos-log.go
dcos-log/journal/reader/config.go
dcos-log/journal/reader/read.go
dcos-log/router/middleware.go
dcos-log/router/router.go
run.sh
vendor/vendor.json

Rest APIs over systemd journal.
Note: this is initial commit, not all functionality is there yet.

add dcos-log

---

dcos-log/api/handlers.go
dcos-log/api/routes.go
dcos-log/journal/reader/config.go
dcos-log/journal/reader/formatters.go
dcos-log/journal/reader/read.go
dcos-log/journal/reader/read_test.go

inspired by
http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

add functional options to journal reader

---

README.md
dcos-log/api/handlers.go
dcos-log/journal/reader/formatters.go

https://www.html5rocks.com/en/tutorials/eventsource/basics/#toc-lastevent-id

add Last-Event-ID support

---

README.md
dcos-log/api/handlers.go
dcos-log/api/handlers_test.go
dcos-log/journal/reader/read.go

add extra response headers which indicate how many entries were actually
skipped.

add X-Journal-Skip-Next, X-Journal-Skip-Prev

---

dcos-log/api/handlers.go
dcos-log/api/routes.go
dcos-log/api/server.go
dcos-log/config/config.go
dcos-log/router/router.go

this will enable `pprof` profiler

add -debug cli option

---

dcos-log/api/handlers.go
dcos-log/api/handlers_test.go
dcos-log/api/routes.go
dcos-log/journal/reader/read.go

this endpoint will return all available unique values for a given field.
this PR depends on https://github.com/coreos/go-systemd/pull/202

add /fields/<field> endpoint

---

dcos-log/api/handlers.go

mutually exclude `read_reverse` and `skip_prev`

handle read_reverse parameters properly

---

dcos-log/api/handlers.go
dcos-log/api/handlers_test.go
dcos-log/api/routes.go

- add /(logs|stream)/container/<container_id>
- refactor `logRoutes`
make dynamic routes loading
- add unittest

add container path

---

dcos-log/api/handlers.go
dcos-log/api/handlers_test.go
dcos-log/api/routes.go

/logs/framework/{framework_id}/executor/{executor_id}/container/{container_id}
/stream/framework/{framework_id}/executor/{executor_id}/container/{container_id}

add UI specific urls

---

dcos-log/api/handlers.go
dcos-log/api/handlers_test.go

we cannot allow all journal fields be exposed. This PR limits allowed fields
based on https://github.com/dcos/dcos-mesos-modules/blob/master/journald/README.md#journald-container-logger-module

filter /fields/<field> endpoint

---

dcos-log/journal/reader/read.go

for the server sent events format we must ping the client to make sure the
connection is not closed.
http://stackoverflow.com/questions/21630509/server-sent-events-connection-timeout-on-node-js-via-nginx
https://html.spec.whatwg.org/multipage/comms.html#authoring-notes

add connection stream keep alive ping

---

dcos-log/journal/reader/config.go
dcos-log/journal/reader/read.go

add option to be able to read the logs since time
taken from https://github.com/coreos/go-systemd/blob/master/sdjournal/read.go#L81

add since option

---

dcos-log/Makefile
dcos-log/api/handlers.go

- add go vet check
- fix potential context leak

dcos-log fixes

---

mergebot-config.json
owners.json

This config change is to enable @mesosphere-mergebot
A webhook needs to be added.
Use of integrate-it and test-it will require write permission for @mesosphere-mergebot to this repo.
Instructions are documented here: https://mesosphere.atlassian.net/wiki/display/DCOS/Mesosphere+Mergebot

Add mergebot config.

---

dcos-log/api/handlers_test.go
dcos-log/api/middleware.go
dcos-log/api/routes.go
dcos-log/api/server.go
dcos-log/config/config.go
vendor/github.com/dcos/dcos-go/dcos/constants.go
vendor/github.com/dcos/dcos-go/dcos/nodeutil/options.go
vendor/github.com/dcos/dcos-go/dcos/nodeutil/util.go
vendor/vendor.json

- bump dcos/nodeinfo vendor folder.
- update code the get the node's role from CLI parameter.

add node's role as a CLI parameter

---

dcos-log/api/server.go
vendor/github.com/dcos/dcos-go/dcos/http/transport/README.md
vendor/github.com/dcos/dcos-go/dcos/http/transport/option.go
vendor/github.com/dcos/dcos-go/dcos/http/transport/roundtripper.go
vendor/github.com/dcos/dcos-go/dcos/http/transport/transport.go
vendor/vendor.json

use dcos transport from shared lib

use dcos-go transport

---

vendor/github.com/dcos/dcos-go/dcos/nodeutil/util.go
vendor/vendor.json

https://github.com/dcos/dcos-go/pull/24

update vendor folder

---

dcos-log/api/middleware.go

remove cookie handling

---

dcos-log/journal/reader/config.go

OptionMatchOR takes a list of EntryMatch objects and and uses OR between
them.

add a functional parameter OptionMatchOR

---

dcos-log/api/v2/handlers.go
dcos-log/api/v2/routes.go
dcos-log/mesos/files/reader/option.go
dcos-log/mesos/files/reader/read.go
dcos-log/mesos/files/reader/read_test.go

- address technical debt from previous review
- add 2 new endpoints for browsing / downloading  files in/from the sandbox
- fixing bugs found during CLI testing

dcos-log v2 improvements 

---

dcos-log/mesos/files/reader/read.go
dcos-log/mesos/files/reader/read_test.go

fix out of range error
